# A generic, single database configuration.

[alembic]
# path to migration scripts
# Use forward slashes (/) also on windows to support an absolute path that is relative to the alembic.ini file
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with the current UTC time.
# file_template = %%(year)d%%(month)s%%(day)s%%(hour)s%%(minute)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use for rendering the date within the migration file
# if not specified, the timezone selected in the Alembic configuration option is used
# default is none
# timezone = UTC+8

# set to 'true' to run the environment during context bodies
# truncate_identity_column = true

# set to 'true' to generate migrations with the 'if exists' clause
# compare_type = implicit

# set to 'true' to use the 'call_return' upgrade token strategy
# call_return = true

[post_write_hooks]
# format migration files with ruff (https://beta.ruff.rs/)
# ruff_format = ruff format --check %%(path)s
# ruff_format_entry = ruff format %%(path)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
